#!/bin/bash
#
# ttanonproxy
# - This is a daemon that running service tor and configure firewall rules to implement
#   a transparent Proxy to TOR;
# - ttanonproxy implement a transparent proxy and avoid any traffic leakage to Internet
#
# v.0.0 - The basic implementation of ttanonproxy

set -e

# Global variables
OS_FAMILY="debian-like"

# Outputs colors
export BLUE='\033[1;94m'
export GREEN='\033[1;92m'
export RED='\033[1;91m'
export RESETCOLOR='\033[1;00m'

# Import the lib
source src/firewall

#check_osfamily () {
# Verify if system running a Debian-like system or RedHat like System
#}

#check_uid () {
# Verify if script was running like root
#}

start () {
  start_firewall
}

if [ "$#" != 0 ]
then
		case "$1" in
			start)
				start_firewall && exit 0
				;;
			stop)
				echo STOP
				;;
			status)
				echo STATUS
				;;
			*)
				echo USE
        exit 3
				;;
		esac
else
	echo "$USE" && exit 2
fi
